feat(orchestrator): add VLAN translation
Updated the JSON configuration.
Added veth_pair APIs to create necessary translations.

Signed-off-by: Ketan Tewari <ktewari@libertyglobal.com>
Change-Id: Ia3986bf15fa5bfae0d736c184a00a46dd690d4cb
Reviewed-on: http://10.64.38.13:8080/gerrit/c/lgi/docker-recipes/+/1478
Reviewed-by: Michele Gualco <mgualco.contractor@libertyglobal.com>
Tested-by: Ketan Tewari <ktewari.contractor@libertyglobal.com>
Reviewed-by: Filippo Carra <fcarra@libertyglobal.com>
Reviewed-by: Ketan Tewari <ktewari.contractor@libertyglobal.com>

diff --git a/orchestrator/init b/orchestrator/init
--- a/orchestrator/init
+++ b/orchestrator/init
@@ -1,10 +1,28 @@
 #!/bin/bash -xe
 
+
+if [ ! -f "/root/config.json" ]; then
+    echo "Cannot run orchestrator without a CONFIG file!"
+    echo "Please mount a config file at /root/config.json !!"
+    exit 1
+fi
+
 # need to initialize and clean ovs modules
 # at least once before running in supervisord
 /usr/share/openvswitch/scripts/ovs-ctl start --system-id=random --ovsdb-server-options='--remote=ptcp:6640'
 /usr/share/openvswitch/scripts/ovs-ctl force-reload-kmod
 /usr/share/openvswitch/scripts/ovs-ctl stop
+
+# Initializing a JSON file as db for OVS to maintain IP range values
+echo "{}" > /tmp/db.json
+
+# Clean all OVS create VETH pairs before creating new ones
+# Since the OVS module is reloaded the DB is clean.
+for iface in $(ip -o link show type veth | cut -d" " -f2 | cut -d"@" -f1); do
+    if [[ "${iface: -2}" == "_c" ]]; then
+        ip link del $iface || true
+    fi
+done
 
 if [ $# -gt 0 ]; then
     /usr/bin/supervisord -c /etc/supervisord.conf
