fix(Dockerfile): update script for aftr
aftr conf and script files to be copied to aftr/ dir

BOARDFARM-5254

Change-Id: I3b39c8f5bb68528d5e6871bb956d7e1f233f0076
Signed-off-by: Vishal Bajpai <vbajpai.ext@libertyglobal.com>
Reviewed-on: http://10.64.38.13:8080/gerrit/c/github/raikou-net/+/9436
Reviewed-by: Michele Gualco <mgualco.contractor@libertyglobal.com>
Tested-by: Michele Gualco <mgualco.contractor@libertyglobal.com>

diff --git a/components/wan/Dockerfile b/components/wan/Dockerfile
--- a/components/wan/Dockerfile
+++ b/components/wan/Dockerfile
@@ -63,6 +63,10 @@ COPY --from=builder /root/aftr /root/aftr
 COPY ./resources/configs/tftpd-hpa/tftpd-hpa.conf /etc/default/tftpd-hpa
 COPY ./init /root/init
 
+RUN printf '## section 0: global parameters\n defmtu 1420\n defmss on\n deftoobig off\n## section 1: required parameters\naddress endpoint\naddress icmp 198.18.200.111\npool 198.18.200.111 tcp 5000-59999\npool 198.18.200.111 udp 5000-59999\npcp 198.18.200.111 tcp 60000-64999\npcp 198.18.200.111 udp 60000-64999\n#All IPv6 ACLs\n' > /root/aftr/aftr.conf
+
+RUN printf '#!/bin/sh \n aftr_start() \n {\n ip link set tun0 up \n sysctl -w net.ipv4.ip_forward=1\n sysctl -w net.ipv6.conf.all.forwarding=1\n sysctl -w net.ipv6.conf.all.disable_ipv6=0\n ip addr add 192.0.0.1 peer 192.0.0.2 dev tun0\n ip route add 198.18.0.0/16 dev tun0\n ip -6 route add \n iptables -t nat -F\n iptables -t nat -A POSTROUTING -s 198.18.200.111 -j SNAT --to-source $PUBLIC\n iptables -t nat -A PREROUTING -p tcp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111\n iptables -t nat -A PREROUTING -p udp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111\n iptables -t nat -A OUTPUT -p tcp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111\n iptables -t nat -A OUTPUT -p udp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111\n }\n aftr_stop()\n {\n iptables -t nat -F\n ip link set tun0 down\n }\n set -x\n PUBLIC=`ip addr show dev eth1 | grep -w inet | awk "{print $2}" | awk -F/ "{print $1}"`\n case "$1" in\n start)\n aftr_start\n ;;\n stop)\n aftr_stop\n ;;\n *)\n echo "Usage: $0 start|stop"\n exit 1\n ;;\n esac\n exit 0\n' > /root/aftr/aftr-script
+
 EXPOSE 69/udp
 EXPOSE 80/tcp
 
